-- supabase/seed.sql

-- Clear existing data
TRUNCATE TABLE resume_sections, projects, project_categories, services, skills, skill_categories RESTART IDENTITY CASCADE;

-- Seed Skill Categories
INSERT INTO skill_categories (id, name_ar, name_en, sort_order) VALUES 
('c1000000-0000-0000-0000-000000000000', 'تطوير الواجهات الخلفية', 'Backend Development', 1),
('c2000000-0000-0000-0000-000000000000', 'تطوير الواجهات الأمامية', 'Frontend Development', 2),
('c3000000-0000-0000-0000-000000000000', 'الاستضافة والأداء', 'Hosting & Performance', 3);

-- Seed Skills
INSERT INTO skills (category_id, name, icon, business_value_ar, business_value_en, sort_order) VALUES 
('c1000000-0000-0000-0000-000000000000', 'Laravel & PHP', 'Database', 'بناء واجهات خلفية آمنة وقابلة للتطوير تتعامل مع حركة مرور عالية وسير عمل معقد بموثوقية.', 'Building secure, scalable backends that handle high traffic and complex business workflows reliably.', 1),
('c1000000-0000-0000-0000-000000000000', 'MySQL', 'Server', 'هيكلة قواعد بيانات قوية تحمي بيانات العملاء الحساسة وتوفر أداء استعلام فوري.', 'Structuring robust databases that protect sensitive client data and provide instant query performance.', 2),
('c2000000-0000-0000-0000-000000000000', 'Tailwind CSS & JavaScript', 'Layout', 'تصميم واجهات مستخدم متجاوبة واحترافية تبني الثقة وتحول الزوار إلى عملاء نشطين.', 'Crafting responsive, premium user interfaces that build trust and convert visitors into active clients.', 3),
('c3000000-0000-0000-0000-000000000000', 'cPanel & Performance', 'Cpu', 'نشر وصيانة وتحسين التطبيقات لضمان وقت تشغيل مستمر بنسبة 99.9% وسرعات تحميل عالية.', 'Deploying, maintaining, and optimizing applications to ensure continuous 99.9% uptime and fast loading speeds.', 4);

-- Seed Services
INSERT INTO services (title_ar, title_en, excerpt_ar, excerpt_en, description_ar, description_en, icon, expected_result_ar, expected_result_en, related_tech, sort_order) VALUES 
('تطوير تطبيقات ويب مخصصة', 'Custom Web Application Development', 'حلول قابلة للتطوير لتلبية احتياجات عملك الفريدة.', 'Scalable solutions for your unique business needs.', 'من لوحات التحكم الداخلية إلى منصات SaaS الموجهة للعملاء، أبني تطبيقات قوية مصممة لتسهيل عملياتك وحل مشاكلك الخاصة.', 'From internal admin dashboards to client-facing SaaS platforms, I build robust applications tailored to streamline your operations and solve your specific bottlenecks.', 'Laptop', 'نظام آمن وسريع وقابل للتطوير يؤتمت المهام ويوفر على فريقك ساعات من العمل اليدوي.', 'A secure, fast, and scalable system that automates tasks and saves your team hours of manual work.', '["Laravel", "Next.js", "MySQL"]', 1),
('تحسين المتاجر الإلكترونية', 'E-Commerce Optimization', 'متاجر عالية التحويل لا تتعطل تحت الضغط.', 'High-converting stores that never crash under pressure.', 'أقوم بتحسين ووكومرس ومتاجر التجارة الإلكترونية للتعامل مع الارتفاع المفاجئ في الزيارات وتقديم تجربة دفع سلسة تزيد من إيراداتك.', 'I optimize WooCommerce and custom e-commerce setups to handle high traffic surges and deliver a frictionless checkout experience that maximizes your revenue.', 'ShoppingCart', 'أوقات تحميل أسرع تؤدي إلى زيادة معدل التحويل وتقليل التخلي عن سلة التسوق بشكل كبير.', 'Faster load times leading to an increased conversion rate and significantly reduced cart abandonment.', '["WooCommerce", "WordPress", "Redis"]', 2),
('تطوير وربط الواجهات البرمجية', 'API Development & Integration', 'ربط أنظمتك المعزولة ببعضها البعض بسلاسة.', 'Connecting your isolated systems together seamlessly.', 'أبني واجهات REST برمجية آمنة للغاية وأقوم بربط خدمات الطرف الثالث مثل بوابات الدفع وأدوات التسويق لأتمتة تدفق بيانات عملك بالكامل.', 'I build highly secure REST APIs and integrate third-party services like payment gateways, CRMs, and marketing tools to fully automate your business data flow.', 'Network', 'تدفق بيانات موثوق وآلي بين أدوات عملك المنفصلة سابقاً، مما يقضي على الإدخال اليدوي.', 'Reliable, automated data flow between your previously disconnected business tools, eliminating manual entry.', '["REST APIs", "PHP", "OAuth"]', 3);

-- Seed Projects
INSERT INTO projects (slug, title_ar, title_en, summary_ar, summary_en, problem_ar, problem_en, goal_ar, goal_en, solution_ar, solution_en, role_ar, role_en, challenges_ar, challenges_en, results_ar, results_en, tech_stack, is_featured, sort_order) VALUES 
('erp-dashboard', 'لوحة تحكم لإدارة موارد الشركة', 'Custom ERP Dashboard', 'لوحة تحكم قابلة للتطوير مبنية بـ Laravel لإدارة الموارد البشرية والمخزون.', 'A scalable Laravel-based dashboard for managing HR and inventory.', 'كان العميل يستخدم جداول إكسل متعددة ومنفصلة لإدارة البيانات، مما تسبب في تأخيرات تشغيلية شديدة.', 'The client was using multiple disconnected Excel sheets to manage data, causing severe operational delays.', 'مركزة العمليات في تطبيق ويب واحد آمن لتحسين الكفاءة.', 'Centralize operations into a single, secure web application to improve efficiency.', 'بناء خلفية Laravel قوية مع واجهة Tailwind CSS متجاوبة، مع ضمان الوصول الآمن بناءً على الأدوار.', 'Built a robust Laravel backend with a responsive Tailwind CSS frontend, ensuring secure role-based access.', 'مطور ويب شامل رئيسي', 'Lead Full Stack Developer', 'ترحيل البيانات القديمة بدون توقف النظام مع الحفاظ على سلامة البيانات.', 'Migrating legacy data without downtime while maintaining data integrity.', 'تقليل وقت إدخال البيانات بنسبة 40% وتحسين دقة التقارير عن طريق القضاء على الإدخالات المكررة.', 'Reduced data entry time by 40% and improved reporting accuracy by eliminating duplicate entries.', '["Laravel", "PHP", "MySQL", "Tailwind CSS"]', true, 1),
('woo-commerce-platform', 'متجر ووكومرس عالي الأداء', 'High-Volume WooCommerce Store', 'منصة تجارة إلكترونية محسنة تتعامل مع آلاف الطلبات اليومية بدون أعطال.', 'Optimized e-commerce platform handling thousands of daily orders without crashes.', 'كان المتجر السابق يتعطل أثناء أحداث الزيارات العالية، مما أدى إلى فقدان المبيعات وإحباط العملاء.', 'The previous store crashed during high traffic events, resulting in lost sales and frustrated customers.', 'ضمان وقت تشغيل 99.9% وسرعة تحميل فائقة أثناء التخفيضات الترويجية.', 'Ensure 99.9% uptime and lightning-fast load speeds during promotional sales.', 'تنفيذ تخزين مؤقت متقدم باستخدام Redis، وتحسين استعلامات قاعدة البيانات البطيئة، وتطوير قالب خفيف مخصص.', 'Implemented advanced caching with Redis, optimized slow database queries, and developed a custom lightweight theme.', 'مهندس خلفية وأداء', 'Backend & Performance Engineer', 'موازنة منطق تسعير سلة التسوق الديناميكية مع التخزين المؤقت القوي على الخادم.', 'Balancing dynamic cart pricing logic with aggressive server-side caching.', 'زيادة معدل التحويل بنسبة 15% والقضاء على وقت التعطل تمامًا خلال مواسم الذروة.', 'Increased conversion rate by 15% and eliminated downtime completely during peak seasons.', '["WordPress", "WooCommerce", "Redis", "PHP"]', true, 2);

-- Seed Resume Sections
INSERT INTO resume_sections (type, title_ar, title_en, organization_ar, organization_en, start_date, end_date, is_current, description_ar, description_en, sort_order) VALUES 
('experience', 'مطور ويب شامل أول', 'Senior Full Stack Developer', 'عمل حر وتعاقدات', 'Freelance & Contracting', '2021', 'Present', true, 'تسليم مشاريع متعددة عالية القيمة بما في ذلك أنظمة تخطيط موارد المؤسسات المعقدة، ومتاجر إلكترونية عالية الزيارات، وواجهات برمجية آمنة لعملاء دوليين، مما أدى إلى نمو ملموس في الأعمال.', 'Delivered multiple high-value projects including complex ERP systems, high-traffic e-commerce stores, and secure APIs for international clients, driving measurable business growth.', 1),
('experience', 'مطور ويب', 'Web Developer', 'وكالة الحلول التقنية', 'Tech Solutions Agency', '2018', '2021', false, 'صيانة وتحديث تطبيقات PHP القديمة إلى المعايير الحديثة. تنفيذ ميزات جديدة ومتجاوبة باستخدام Laravel وأطر عمل JavaScript الحديثة، مما أدى إلى تحسين الاحتفاظ بالمستخدمين.', 'Maintained and upgraded legacy PHP applications to modern standards. Implemented new, responsive features using Laravel and modern JavaScript frameworks, improving user retention.', 2);
